@extends('layout.entrance')
@section('content')
                    <div class="panel-body">
                    <form class="form-vertical" role="form" method="POST" action="{{ route('createReserved')}}">
                        {{csrf_field()}}
                        <div class="form-group">
                        <label for="NameCustomer"> Customer Name </label>
                            <input type="text" id="NameCustomer" name="customerName" class="form-control" placeholder="Customer Name">
                        </div>
                        <div class="form-group">
                        <label for="EmailCustomer"> Customer Email </label>
                            <input type="email" id="EmailCustomer" name="customerEmail" class="form-control" placeholder="Customer Email">
                        </div>
                        <div class="form-group">
                        <label for="Currency"> Currency </label>
                            <input type="text" id="Currency" name="currency" value="NGN" readonly="readonly" class="form-control" placeholder="Currency">
                        </div>
                        <div class="form-group">
                        <label for="AccountName"> Account Name </label>
                            <input type="text" id="AccountName" name="accountName" class="form-control" placeholder="Account Name">
                        </div>
                        <div class="form-group">
                        <label for="References"> References </label>
                            <div class="alert alert-info" role="alert">
                           <p><strong>Nb:</strong> The Reference code will be generated by the system.</p>
                            </div>
                        </div>
                        <div class="form-group">
                        <label for="contract"> Contract </label>
                            <input type="text" name="contractCode" value="2957982769" readonly="readonly" id="Contract" class="form-control" placeholder="Contract">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-info">Reserve Account</button>
                        </div>
                    </form>
                            
                    </div>

               
@stop